/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ReportsRouteImport } from "./routes/reports";
import { Route as IssuesRouteImport } from "./routes/issues";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any);
const IssuesRoute = IssuesRouteImport.update({
  id: "/issues",
  path: "/issues",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/issues": typeof IssuesRoute;
  "/login": typeof LoginRoute;
  "/reports": typeof ReportsRoute;
  "/register": typeof RegisterRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/issues": typeof IssuesRoute;
  "/login": typeof LoginRoute;
  "/reports": typeof ReportsRoute;
  "/register": typeof RegisterRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/issues": typeof IssuesRoute;
  "/login": typeof LoginRoute;
  "/reports": typeof ReportsRoute;
  "/register": typeof RegisterRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard" | "/forgot-password" | "/issues" | "/login" | "/reports" | "/register" | "/settings";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard" | "/forgot-password" | "/issues" | "/login" | "/reports" | "/register" | "/settings";
  id: "__root__" | "/" | "/dashboard" | "/forgot-password" | "/issues" | "/login" | "/reports" | "/register" | "/settings";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  IssuesRoute: typeof IssuesRoute;
  LoginRoute: typeof LoginRoute;
  ReportsRoute: typeof ReportsRoute;
  RegisterRoute: typeof RegisterRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports": {
      id: "/reports";
      path: "/reports";
      fullPath: "/reports";
      preLoaderRoute: typeof ReportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/issues": {
      id: "/issues";
      path: "/issues";
      fullPath: "/issues";
      preLoaderRoute: typeof IssuesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
